urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template
from laws.views import * 
from django.contrib import admin
import os

admin.autodiscover()

# Set up the databrowse application
from django.contrib import databrowse
from laws.models import Code, SectionFile, Section

#databrowse.site.register(Code)
#databrowse.site.register(SectionFile)
#databrowse.site.register(Section)

#admin.site.register(Code)
#admin.site.register(SectionFile)
#admin.site.register(Section)


handler404 = 'calaw.laws.views.my404'

urlpatterns = patterns('',
    # Example:
    # (r'^calaw/', include('calaw.foo.urls')),
    
    # Target urls:
      url(r'^laws/target/.*?', 'laws.views.target_remove'),

    # Statutes:
      url(r'^laws/CODE-(?P<codename>[a-z]{3,4})-(?P<target_section>[0-9.]*)/?', 'laws.views.target_to_section', name='section'),

    # Code tables of contents:
      url(r'^laws/C(?:ODE|ode)-(?P<codename>[a-z]{3,4})/?', 'laws.views.code_toc', name='code_toc'),

    # Enamble admin documentation:
      (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Enable the admin:
      url(r'^admin/', include(admin.site.urls), name='admin'),
    
    # Allow browsing of the data
    #  (r'^databrowse/(.*)', 'databrowse.site.root'),

    # Search page and results
       url(r'^search/?$', 'laws.views.search', name='search'),

    # Default to the index
    url(r'^$', 'laws.views.codes_index', name='codes_toc'),
)

if settings.DEBUG: # Serve static files in debug.
    urlpatterns += patterns('', (r'^site_media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes' : True}), )

laws/models.py
from django.db import models
from django import forms 
from djangosphinx.models import SphinxQuerySet

# Create your models here.
class Code(models.Model):
    name = models.CharField(max_length=4)
    fullname = models.CharField(max_length=255) 
    url = models.CharField(max_length=255)
    def __unicode__(self):
        return self.name #self.title

class Section(models.Model):
    secnumber= models.CharField(max_length=10)
    text = models.TextField(null=True, blank=True)
    code = models.ForeignKey('Code')
    sectionfile = models.ForeignKey('SectionFile')
    def __unicode__(self):
        return self.secnumber #self.secnumber

class SectionFile(models.Model):
    sectionfile = models.CharField(max_length=20)
    code = models.ForeignKey('Code')
    text = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=255)
    sectionfilename = models.ForeignKey('SectionFileName', blank=True, null=True, on_delete=models.SET_NULL)
    
    def __unicode__(self):
        return self.sectionfile #self.sectionfile

class SectionFileIndex(models.Model):
    sectionfile = models.CharField(max_length=20)
    code = models.ForeignKey('Code')
    text = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return self.sectionfile #self.sectionfile
    
    search = SphinxQuerySet(
        index = 'calaw1',
        weights = { # individual field weighting
            'sectionfile': 0,
            'code': 0,
            'text': 100,
            'url': 0,
        },
        mode = 'SPH_MATCH_EXTENDED2',
        rankmode = 'SPH_RANK_SPH04',
        #"Only_Sphinx" mode makes search independent from the db; necessary when using a db that is not supported by Sphinx (e.g. sqlite)
        #Found in a git branch of the djangosphinx code
        only_sphinx = True
    )
       
    class Meta:
        db_table = 'calaw1'

class SectionFileName(models.Model):
    name = models.CharField(max_length=255)
    parents = models.CharField(max_length=255)

    def __unicode__(self):
        return self.parents #self.name

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class":"right_btn", "onfocus":"$('#id_query').css('background','none'); var q=$('#id_query').val(); if (q=='Search...') {$('#id_query').val(''); $('#id_query').css('font-weight','bolder');}","onblur":"var q=$('#id_query').val(); \r\n if (q=='') {$('#id_query').val('Search...'); $('#id_query').css('font-weight','normal'); $('#id_query').css('background', 'transparent url(/site_media/img/icons/magnifier.png) no-repeat scroll right center'); } "}), initial="Search...", label="Search...")
    page = forms.IntegerField(widget=forms.HiddenInput())

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>{% block title %}CA Law{% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="initial-scale=1,maximum-scale=1,minimum-scale=1 user-scalable=no,width = 320" />
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />        
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/reset.css" />
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/typography.css" />
        <link rel="stylesheet" type="text/css" media="all" href="{{ MEDIA_URL }}css/style.css" />
        <link href="{{ MEDIA_URL }}img/favicon.png" rel='shortcut icon' /> 
        <link href="{{ MEDIA_URL }}img/favicon.png" rel='icon' />
        <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.4.4.min.js"></script>
        <script type="text/javascript">
              var _gaq = _gaq || [];
              _gaq.push(['_setAccount', 'UA-10416851-3']);
              _gaq.push(['_trackPageview']);

              (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
              })();
        </script>
        {% block extrahead %}
        {% endblock %}
    </head>
    {% block navbar %}
        {% include 'navigation.html' %}<br/>    
    {% endblock navbar %}
    {%  block search %}
    {% endblock search %}
    {%  block content %}
    {%  endblock content %}
</html>

templates/base_search.html
{% extends 'base.html' %}
{% block navbar %}
        {% include 'navigation.html' %}    
{% endblock navbar %}
{%  block search %}
{% endblock search %}
{%  block content %}
{%  endblock content %}

templates/code_display.html
    {% extends 'base.html' %}
    {% block navbar %}
        {% include 'navigation.html' %}    
    {% endblock navbar %}
    {%  block content %}
        {{ body|safe }}
    {%  endblock content %}

templates/code_toc.html
    {% extends 'base.html' %}
    {%  block content %}
        {{ body|safe }}
    {%  endblock content %}

templates/navigation.html
{% load base_extras %}
<div id="topbar">
    <div class="navbar">
        <div class="navbar-side navbar-left">
        </div>
        <div class="navbar-content">
           {% comment %}    {% if user.is_authenticated %}  {% endif %}  {% endcomment  %}
            <a class="{% navactive request 'codes_toc' %}"
                href="{% url codes_toc %}">CA Codes</a>
            {% comment %}TODO: Remove the hardcoded CSS and pass styling through the View{% endcomment %}
            {% if code_fn %}
                &nbsp;&nbsp;>> &nbsp;&nbsp;
                <a class="" style="font-weight: bold" href="/laws/CODE-{{code_current}}">{{ code_fn }}</a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                <a href="{% url search %}" class="{% navactive request 'search' %}">Search</a>
            {% endif %}
                {% if parents %}
                    <span class="toggle_link" style="font-size: 80%;">
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <button onclick="$('#parents').toggle();$('#Hide').toggle();$('#Show').toggle();" style="background: #D3D3D3; font-size: 110%; -webkit-appearance: none;" id='Hide'>Hide</button>
                        <button onclick="$('#parents').toggle();$('#Hide').toggle();$('#Show').toggle(); "style="background: #D3D3D3; font-size: 110%; display: none; -webkit-appearance: none;" id='Show'>Show</button>
                        <span class="hideable" id="parents">
                             <br/> {{ parents }} <br/>
                        </span>
                    </span>
                {% endif %}
                        
        </div>
        <div class="navbar-side navbar-right"></div>
    </div>
</div>

templates/paginator.html
  <div class="width100 left">
  {% if page.has_previous %}
  <a href='?p={{ page.previous_page_number }}'>&lt;&lt; Previous</a>
  {% endif %}
  Page {{ page.number }} of {{ page.paginator.num_pages }}
  {% if page.has_next %}
  <a href='?p={{ page.next_page_number }}'>Next &gt;&gt;</a>
  {% endif %}
  </div>

templates/right_panel_search.html
{% if searchform %}
<div class="left" style="margin-bottom:20px; position: absolute; left: 500px;">
    <form method="post" action="/search" id="id_search_form" onSubmit="if ($('#id_query').val()=='{{ searchform.query.label }}') {
        return false;}">{% csrf_token %}
    <div class="left">    
      {{ searchform.query }}
<!-- {{ searchform.query.errors }} -->  
    </div>
    <div class="left" style="padding-top:5px;">
      <div class="left">
	<input type="submit" value="Go!" class="right_btn find_btn" style="width:100px;" />  
      </div>
      <input type="hidden" name="page" value = "1" id="id_page"/>
    </div>
  </form>
</div>
{% endif %}

templates/search.html
{% extends 'base.html' %}
{% block navigation %}
    {% include navigation.html %}
{% endblock navigation %}
{% block search %}
    <div id="search_main">
        {% autoescape on %} 
            <div style="padding:5px; border-bottom:1px dashed gray; margin-bottom:20px;">
                <h1>Search:</h1>
                <form method="post" id="id_search_form" onsubmit="if ($('#id_query').val()=='Search...') {return false;}">{% csrf_token %}
                    {{ searchform.query }} {{ searchform.query.errors }}  
                    <input type="hidden" name="page" value = "1" id="id_page"/> <input type="submit" value="Go!" class="right_btn find_btn" style="width:100px;"/>  
                </form>
                <p><span style="text-decoration:underline">Total # of results:</span>&nbsp;{{total}}</p>
            </div>
        {% endautoescape %}
    </div>
{% endblock search %}
{% block content %}
    <div id="results_main">
        <h4>{% if total > 20 %}TOP 20 RESULTS:{% endif %}</h4>
        {% for sectionfile, rpassage in rpassages %}
            <div class="list_item pointer" id="item-{{ sectionfile.id }}" onclick="location.href='/laws/target/CODE-{{sectionfile.code}}-{{sectionfile}}';">
	           <a href="/laws/target/CODE-{{sectionfile.code}}-{{sectionfile}}" class="sec">{{sectionfile.code.fullname}}, Sections: {{ sectionfile }}</a>
               <div style="margin-top:5px; margin-bottom:30px; text-indent:50px;">{{rpassage|safe}}
            </div>
        {% empty %}
            <p>No results found.</p>
        {% endfor %}
       <!-- {% include "paginator.html" %} -->
    </div>
{% endblock content %}